# Generated by Django 4.2.16 on 2024-10-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_recipe_is_favorited_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Список покупок'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Список покупок'},
        ),
    ]
