version: '3.3'

volumes:
  static_foodgram:
  media_foodgram:
  pg_data_foodgram:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: closecodex/foodgram_backend
    env_file: .env
    volumes:
      - media_foodgram:/media/
      - static_foodgram:/app/static/

  frontend:
    container_name: foodgram-front
    image: closecodex/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: closecodex/foodgram_proxy
#   build: .
#   image: nginx:1.25.4-alpine
    ports:
      - "8080:80"
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_foodgram:/media/
      - static_foodgram:/static/