# Generated by Django 3.2.3 on 2024-10-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241020_0116'),
    ]

    operations = [
    ]
