# Generated by Django 3.2.3 on 2024-10-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241020_1756'),
    ]

    operations = [
    ]
